routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

Route::group(['middleware' => ['throttle:30,1']], function () {
    // Home
    Route::get('/', [HomeController::class, 'index'])->name('home');

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('export', [UserController::class, 'exportAccount'])->name('export');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::get('suspended', [UserController::class, 'suspended'])->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::get('users', [AdminController::class, 'users'])->name('users');
        Route::get('tasks', [AdminController::class, 'tasks'])->name('tasks');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::get('', [PatronController::class, 'patron'])->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::get('tasks', [TaskController::class, 'tasks'])->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('reputation', 'pages.reputation')->name('reputation');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::get('open', [PagesController::class, 'open'])->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    Route::get('meetups', [MeetupController::class, 'meetups'])->name('meetups')->middleware('staff');

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status
    Route::group(['prefix' => 'status'], function () {
        Route::get('ping', [StatusController::class, 'ping']);
        Route::get('redis', [StatusController::class, 'redis']);
        Route::get('memcached', [StatusController::class, 'memcached']);
    });
});

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Hovercard
Route::group(['prefix' => 'hovercard'], function () {
    Route::get('user/{id}', [UserController::class, 'hovercard']);
    Route::get('product/{id}', [ProductController::class, 'hovercard']);
});

app/Http/Livewire/Admin/Adminbar.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Answer;
use App\Models\Comment;
use App\Models\Product;
use App\Models\Question;
use App\Models\Task;
use App\Models\User;
use App\Models\Webhook;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Queue;
use Livewire\Component;

class Adminbar extends Component
{
    protected $listeners = [
        'refreshStats' => 'render',
    ];

    public function refreshStats()
    {
        $this->emitSelf('refreshStats');
    }

    public function render()
    {
        if (file_exists('../.git/HEAD')) {
            $branch = File::get('../.git/HEAD');
            $explodedstring = explode('/', $branch, 3);
            $branchname = str_replace("\n", '', $explodedstring[2]);
        } else {
            $branchname = 'master';
        }
        if (file_exists('../VERSION')) {
            $version = File::get('../VERSION');
        } else {
            $version = '0.0.0';
        }

        // DB Details
        $tasks = Task::count('id');
        $users = User::count('id');
        $products = Product::count('id');
        $reputations = User::sum('reputation');
        $questions = Question::count('id');
        $answers = Answer::count('id');
        $comments = Comment::count('id');
        $webhooks = Webhook::count('id');
        $notifications = DB::table('notifications')->count();
        $praises = DB::table('interactions')->whereRelation('like')->count();
        $jobs = Queue::size();

        return view('livewire.admin.adminbar', [
            'version' => $version,
            'branchname' => $branchname,
            'tasks' => number_format($tasks),
            'users' => number_format($users),
            'products' => number_format($products),
            'reputations' => number_format($reputations),
            'questions' => number_format($questions),
            'answers' => number_format($answers),
            'comments' => number_format($comments),
            'notifications' => number_format($notifications),
            'praises' => number_format($praises),
            'jobs' => number_format($jobs),
            'webhooks' => number_format($webhooks),
        ]);
    }
}

app/Http/Livewire/Answer/Answers.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Answers extends Component
{
    public $listeners = [
        'answerAdded' => 'render',
        'answerDeleted' => 'render',
    ];

    public $question;
    public $page;
    public $perPage;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        $answers = Answer::cacheFor(60 * 60)
            ->where('question_id', $this->question->id)
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                ]);
            })
            ->orderBy('created_at', 'DESC')
            ->get();

        return view('livewire.answer.answers', [
            'answers' => $this->paginate($answers),
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Answer/CreateAnswer.php
<?php

namespace App\Http\Livewire\Answer;

use App\Gamify\Points\CommentCreated;
use App\Models\Answer;
use App\Notifications\Answered;
use Helper;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class CreateAnswer extends Component
{
    public $answer;
    public $question;

    public function mount($question)
    {
        $this->question = $question;
    }

    public function updated($field)
    {
        if (Auth::check()) {
            $this->validateOnly($field, [
                'answer' => 'required',
            ]);
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function submit()
    {
        if (Auth::check()) {
            $this->validate([
                'answer' => 'required',
            ]);

            if (! Auth::user()->hasVerifiedEmail()) {
                return session()->flash('warning', 'Your email is not verified!');
            }

            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            $users = Helper::getUserIDFromMention($this->answer);

            $answer = Answer::create([
                'user_id' =>  Auth::id(),
                'question_id' =>  $this->question->id,
                'answer' => $this->answer,
            ]);
            Auth::user()->touch();

            $this->emit('answerAdded');
            $this->answer = '';
            Helper::mentionUsers($users, $answer, 'answer');
            Helper::notifySubscribers($answer->question->subscribers, $answer, 'answer');
            if (! Auth::user()->hasSubscribed($answer->question)) {
                Auth::user()->subscribe($answer->question);
                $this->emit('questionSubscribed');
            }
            if (Auth::id() !== $this->question->user->id) {
                $this->question->user->notify(new Answered($answer));
                givePoint(new CommentCreated($answer));
            }

            return session()->flash('success', 'Answer has been added!');
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.answer.create-answer');
    }
}

app/Http/Livewire/Answer/LoadMore.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $question;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $answers = Answer::cacheFor(60 * 60)
                ->where('question_id', $this->question->id)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                    ]);
                })
                ->get();

            return view('livewire.answer.answers', [
                'answers' => $this->paginate($answers),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Home/OnlyFollowing.php
<?php

namespace App\Http\Livewire\Home;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class OnlyFollowing extends Component
{
    public function onlyFollowingsTasks()
    {
        if (Auth::check()) {
            Auth::user()->onlyFollowingsTasks = ! Auth::user()->onlyFollowingsTasks;
            Auth::user()->save();
            $this->emit('onlyFollowings');
        } else {
            return session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.home.only-following');
    }
}

app/Http/Livewire/Meetup/SingleMeetup.php
<?php

namespace App\Http\Livewire\Meetup;

use Livewire\Component;

class SingleMeetup extends Component
{
    public $meetup;

    public function mount($meetup)
    {
        $this->meetup = $meetup;
    }

    public function render()
    {
        return view('livewire.meetup.single-meetup');
    }
}

resources/views/livewire/admin/adminbar.blade.php
<div class="card p-1 rounded-0 d-flex border-bottom border-primary bg-primary text-white">
    <div class="pl-2 pr-2">
        <span class="float-left">
            <a class="text-white font-weight-bold" href="https://gitlab.com/taskord/taskord/-/tree/{{ $branchname }}" target="_blank">
                <i class="fa fa-code-branch mr-1"></i>
                {{ $branchname }}
            </a>
            <a class="text-white font-weight-bold ml-3" href="https://gitlab.com/taskord/taskord/-/releases/v{{ $version }}" target="_blank">
                <i class="fa fa-cube mr-1"></i>
                v{{ $version }}
            </a>
            <a class="text-white font-weight-bold ml-3" href="https://github.com/laravel/framework/releases/tag/v{{ App::VERSION() }}" target="_blank">
                <i class="fab fa-laravel mr-1"></i>
                Laravel v{{ App::VERSION() }}
            </a>
            <a class="text-white font-weight-bold ml-3" href="http://git.php.net/?p=php-src.git;a=shortlog;h=refs/heads/PHP-{{ phpversion() }}" target="_blank">
                <i class="fab fa-php mr-1"></i>
                PHP v{{ phpversion() }}
            </a>
        </span>
        <span class="float-right">
            <span role="button" class="dropdown dropleft">
                <span class="font-weight-bold mr-3" data-toggle="dropdown">
                    <i class="fa fa-chart-pie mr-1"></i>
                    Stats
                </span>
                <ul class="dropdown-menu shadow-sm border">
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-check mr-1"></i>
                            <span class="font-weight-bold">{{ $tasks }}</span> Tasks
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-users mr-1"></i>
                            <span class="font-weight-bold">{{ $users }}</span> Users
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-box-open mr-1"></i>
                            <span class="font-weight-bold">{{ $products }}</span> Products
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-question-circle mr-1"></i>
                            <span class="font-weight-bold">{{ $questions }}</span> Questions
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-comments mr-1"></i>
                            <span class="font-weight-bold">{{ $answers }}</span> Answers
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-comment mr-1"></i>
                            <span class="font-weight-bold">{{ $comments }}</span> Comments
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-fire mr-1"></i>
                            <span class="font-weight-bold">{{ $reputations }}</span> Reputations
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-thumbs-up mr-1"></i>
                            <span class="font-weight-bold">{{ $praises }}</span> Praises
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-bell mr-1"></i>
                            <span class="font-weight-bold">{{ $notifications }}</span> Notifications
                        </span>
                    </li>
                    <li class="dropdown-item">
                        <span class="mr-3">
                            <i class="fa fa-anchor mr-1"></i>
                            <span class="font-weight-bold">{{ $webhooks }}</span> Webhooks
                        </span>
                    </li>
                    <div class="dropdown-divider"></div>
                    <li class="dropdown-item" wire:click="refreshStats">
                        <span class="mr-3">
                            <i class="fa fa-sync-alt mr-1"></i>
                            Refresh
                        </span>
                    </li>
                </ul>
            </span>
            <a class="font-weight-bold mr-3 text-white" href="/admin/horizon" target="_blank">
                <i class="fa fa-wrench mr-1"></i>
                {{ $jobs }}
                <span class="font-weight-normal">
                    jobs
                </span>
            </a>
            <span class="font-weight-bold mr-3">
                <i class="fa fa-clock mr-1"></i>
                {{ round(microtime(true) - LARAVEL_START, 2) * 1000 }}ms
                <span class="font-weight-normal">response total</span>
            </span>
            <span class="font-weight-bold mr-3">
                <a href="/graphiql" target="_blank">
                    <i class="fa fa-sitemap text-white"></i>
                </a>
            </span>
            <span class="font-weight-bold">
                <a href="{{ route('admin.users') }}">
                    <i class="fa fa-rocket text-white"></i>
                </a>
            </span>
        </span>
    </div>
</div>