routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

Route::group(['middleware' => ['throttle:30,1']], function () {
    // Home
    Route::get('/', [HomeController::class, 'index'])->name('home');

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('export', [UserController::class, 'exportAccount'])->name('export');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::get('suspended', [UserController::class, 'suspended'])->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::get('users', [AdminController::class, 'users'])->name('users');
        Route::get('tasks', [AdminController::class, 'tasks'])->name('tasks');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::get('', [PatronController::class, 'patron'])->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::get('tasks', [TaskController::class, 'tasks'])->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('reputation', 'pages.reputation')->name('reputation');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::get('open', [PagesController::class, 'open'])->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    Route::get('meetups', [MeetupController::class, 'meetups'])->name('meetups')->middleware('staff');

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status
    Route::group(['prefix' => 'status'], function () {
        Route::get('ping', [StatusController::class, 'ping']);
        Route::get('redis', [StatusController::class, 'redis']);
        Route::get('memcached', [StatusController::class, 'memcached']);
    });
});

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Hovercard
Route::group(['prefix' => 'hovercard'], function () {
    Route::get('user/{id}', [UserController::class, 'hovercard']);
    Route::get('product/{id}', [ProductController::class, 'hovercard']);
});

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Comment;
use App\Models\Product;
use App\Models\Question;
use App\Models\Task;
use App\Models\User;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    public function search()
    {
        $phrases = [
            number_format(Task::cacheFor(60 * 60)->count('id')).' tasks',
            number_format(Comment::cacheFor(60 * 60)->count('id')).' task comments',
            number_format(Question::cacheFor(60 * 60)->count('id')).' questions',
            number_format(User::cacheFor(60 * 60)->count('id')).' users',
            number_format(Product::cacheFor(60 * 60)->count('id')).' products',
        ];

        return view('search.search', [
            'random' => $phrases[array_rand($phrases)],
        ]);
    }

    public function tasks(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $tasks = Task::cacheFor(60 * 60)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                        ['isPrivate', false],
                    ]);
                })
                ->where('hidden', false)
                ->where('task', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($tasks) === 0) {
                $tasks = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'tasks',
            'searchTerm' => $searchTerm,
            'tasks' =>  $tasks,
        ]);
    }

    public function comments(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $comments = Comment::cacheFor(60 * 60)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                        ['isPrivate', false],
                    ]);
                })
                ->where('hidden', false)
                ->where('comment', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($comments) === 0) {
                $comments = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'comments',
            'searchTerm' => $searchTerm,
            'comments' =>  $comments,
        ]);
    }

    public function questions(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $questions = Question::cacheFor(60 * 60)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                    ]);
                })
                ->where('hidden', false)
                ->where('title', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($questions) === 0) {
                $questions = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'questions',
            'searchTerm' => $searchTerm,
            'questions' =>  $questions,
        ]);
    }

    public function answers(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $answers = Answer::cacheFor(60 * 60)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                    ]);
                })
                ->where('hidden', false)
                ->where('answer', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($answers) === 0) {
                $answers = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'answers',
            'searchTerm' => $searchTerm,
            'answers' =>  $answers,
        ]);
    }

    public function products(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $products = Product::cacheFor(60 * 60)
                ->whereHas('owner', function ($q) {
                    $q->where([
                        ['isFlagged', false],
                    ]);
                })
                ->where('slug', 'LIKE', '%'.$searchTerm.'%')
                ->orWhere('name', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($products) === 0) {
                $products = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'products',
            'searchTerm' => $searchTerm,
            'products' =>  $products,
        ]);
    }

    public function users(Request $request)
    {
        $searchTerm = $request->input('q');
        if ($searchTerm) {
            $users = User::cacheFor(60 * 60)
                ->where('username', 'LIKE', '%'.$searchTerm.'%')
                ->orWhere('firstname', 'LIKE', '%'.$searchTerm.'%')
                ->orWhere('lastname', 'LIKE', '%'.$searchTerm.'%')
                ->paginate(10)
                ->onEachSide(1);
            if (count($users) === 0) {
                $users = null;
            }
        } else {
            return redirect()->route('search.home');
        }

        return view('search.result', [
            'type' => 'users',
            'searchTerm' => $searchTerm,
            'users' =>  $users,
        ]);
    }
}

app/Http/Livewire/Search.php
<?php

namespace App\Http\Livewire;

use App\Models\Product;
use App\Models\Question;
use App\Models\Task;
use App\Models\User;
use Livewire\Component;

class Search extends Component
{
    public $query;
    public $tasks;
    public $users;
    public $products;
    public $questions;

    public function mount()
    {
        $this->query = '';
        $this->tasks;
        $this->users;
        $this->products;
        $this->questions;
    }

    public function updatedQuery()
    {
        $this->tasks = Task::cacheFor(60 * 60)
            ->select('id', 'task', 'done', 'hidden', 'user_id')
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                    ['isPrivate', false],
                ]);
            })
            ->where('hidden', false)
            ->where('task', 'LIKE', '%'.$this->query.'%')
            ->take(3)
            ->get();
        $this->users = User::cacheFor(60 * 60)
            ->select('username', 'firstname', 'lastname', 'avatar', 'isVerified')
            ->where('username', 'LIKE', '%'.$this->query.'%')
            ->orWhere('firstname', 'LIKE', '%'.$this->query.'%')
            ->orWhere('lastname', 'LIKE', '%'.$this->query.'%')
            ->take(3)
            ->get();
        $this->products = Product::cacheFor(60 * 60)
            ->select('slug', 'name', 'avatar', 'user_id')
            ->where('slug', 'LIKE', '%'.$this->query.'%')
            ->orWhere('name', 'LIKE', '%'.$this->query.'%')
            ->take(3)
            ->get();
        $this->questions = Question::cacheFor(60 * 60)
            ->select('id', 'title', 'user_id')
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                ]);
            })
            ->where('hidden', false)
            ->where('title', 'LIKE', '%'.$this->query.'%')
            ->take(3)
            ->get();
    }

    public function render()
    {
        return view('livewire.search');
    }
}

resources/views/search/result.blade.php
@extends('layouts.app')

@section('pageTitle', 'Search · '.$searchTerm.' ·')
@section('title', 'Search · '.$searchTerm.' ·')
@section('description', 'Browse questions and discuss, answer, give feedbacks, etc.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="row justify-content-center">
        <div class="col-sm">
            @include('search.sidebar')
        </div>
        <div class="col-lg-8">
            @if ($type === 'tasks')
                <form action="/search/tasks" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search tasks">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$tasks)
                <x-empty icon="search" text="We couldn’t find any tasks matching '{{ $searchTerm }}'" />
                @else
                @foreach ($tasks as $task)
                <li class="list-group-item p-3">
                    @livewire('task.single-task', [
                        'task' => $task
                    ], key($task->id))
                </li>
                @endforeach
                <div class="mt-3">
                    {{ $tasks->appends(request()->input())->links() }}
                </div>
                @endif
            @endif

            @if ($type === 'comments')
                <form action="/search/comments" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search comments">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$comments)
                <x-empty icon="search" text="We couldn’t find any comments matching '{{ $searchTerm }}'" />
                @else
                @foreach ($comments as $comment)
                @livewire('comment.single-comment', [
                    'comment' => $comment,
                ], key($comment->id))
                @endforeach
                <div class="mt-3">
                    {{ $comments->appends(request()->input())->links() }}
                </div>
                @endif
            @endif

            @if ($type === 'questions')
                <form action="/search/questions" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search questions">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$questions)
                <x-empty icon="search" text="We couldn’t find any questions matching '{{ $searchTerm }}'" />
                @else
                @foreach ($questions as $question)
                @livewire('question.single-question', [
                    'type' => 'questions.newest',
                    'question' => $question,
                ], key($question->id))
                @endforeach
                <div class="mt-3">
                    {{ $questions->appends(request()->input())->links() }}
                </div>
                @endif
            @endif

            @if ($type === 'answers')
                <form action="/search/answers" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search answers">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$answers)
                <x-empty icon="search" text="We couldn’t find any answers matching '{{ $searchTerm }}'" />
                @else
                @foreach ($answers as $answer)
                    <div class="card mb-2">
                        <div class="card-header h6 pt-3 pb-3">
                            <a href="{{ route('user.done', ['username' => $answer->question->user->username]) }}">
                                <img class="rounded-circle avatar-30" src="{{ $answer->question->user->avatar }}" />
                            </a>
                            <a class="align-middle text-dark ml-2" href="{{ route('question.question', ['id' => $answer->question->id]) }}">
                                {{ $answer->question->title }}
                            </a>
                        </div>
                        @livewire('answer.single-answer', [
                            'answer' => $answer
                        ], key($answer->id))
                    </div>
                @endforeach
                <div class="mt-3">
                    {{ $answers->appends(request()->input())->links() }}
                </div>
                @endif
            @endif

            @if ($type === 'products')
                <form action="/search/products" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search products">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$products)
                <x-empty icon="search" text="We couldn’t find any products matching '{{ $searchTerm }}'" />
                @else
                @foreach ($products as $product)
                    <li class="list-group-item pt-3 pb-3">
                        <div class="d-flex align-items-center">
                            <a href="{{ route('product.done', ['slug' => $product->slug]) }}">
                                <img class="rounded avatar-50 mt-1 ml-2" src="{{ $product->avatar }}" height="50" width="50" />
                            </a>
                            <span class="ml-3">
                                <a href="{{ route('product.done', ['slug' => $product->slug]) }}" class="mr-2 h5 align-text-top font-weight-bold text-dark">
                                    {{ $product->name }}
                                    @if ($product->launched)
                                        <a href="{{ route('products.launched') }}" class="small" data-toggle="tooltip" data-placement="right" title="Launched">
                                            {{ Emoji::rocket() }}
                                        </a>
                                    @endif
                                    @if ($product->deprecated)
                                        <span class="ml-1 small" title="Deprecated">
                                            <i class="fa fa-ghost text-danger"></i>
                                        </span>
                                    @endif
                                </a>
                                <div class="text-black-50 mb-2">
                                    {{ "#" . $product->slug }}
                                </div>
                                <div>{{ $product->description }}</div>
                                <div class="small mt-2">
                                    <i class="fa fa-calendar-alt mr-1 text-black-50"></i>
                                    <span>Lauched at {{ Carbon::parse($product->launched_at)->format("F Y") }}</span>
                                </div>
                                <div class="mt-3">
                                    @livewire('product.subscribe', [
                                        'product' => $product
                                    ], key($product->id))
                                </div>
                            </span>
                            <a class="ml-auto" href="{{ route('user.done', ['username' => $product->owner->username]) }}">
                                <img class="rounded-circle float-right avatar-30 mt-1 ml-2" src="{{ $product->owner->avatar }}" height="50" width="50" />
                            </a>
                        </div>
                    </li>
                @endforeach
                <div class="mt-3">
                    {{ $products->appends(request()->input())->links() }}
                </div>
                @endif
            @endif

            @if ($type === 'users')
                <form action="/search/users" method="GET" role="search">
                    @csrf
                    <div class="input-group mb-4">
                        <input type="text" class="form-control" name="q" value="{{ $searchTerm }}" placeholder="Search users">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
                @if (!$users)
                <x-empty icon="search" text="We couldn’t find any users matching '{{ $searchTerm }}'" />
                @else
                @foreach ($users as $user)
                    <li class="list-group-item pt-3 pb-3">
                        <div class="d-flex align-items-center">
                            <a href="{{ route('user.done', ['username' => $user->username]) }}">
                                <img class="rounded-circle avatar-50 mt-1 ml-2" src="{{ $user->avatar }}" height="50" width="50" />
                            </a>
                            <span class="ml-3">
                                <a href="{{ route('user.done', ['username' => $user->username]) }}" class="mr-2 h5 align-text-top font-weight-bold text-dark">
                                    @if ($user->firstname or $user->lastname)
                                        {{ $user->firstname }}{{ ' '.$user->lastname }}
                                    @else
                                        {{ $user->username }}
                                    @endif
                                    @auth
                                    @if (Auth::user()->staffShip)
                                        <span class="ml-2 text-secondary small">#{{ $user->id }}</span>
                                    @endif
                                    @endauth
                                    @if ($user->isPatron)
                                        <a class="ml-2 small" href="{{ route('patron.home') }}" title="Patron">
                                            {{ Emoji::handshake() }}
                                        </a>
                                    @endif
                                    @auth
                                    @if ($user->isFollowing(Auth::user()))
                                        <span class="ml-2 badge bg-light text-black-50">Follows you</span>
                                    @endif
                                    @endauth
                                </a>
                                <div class="text-black-50 mb-2">
                                    {{ "@" . $user->username }}
                                </div>
                                <div>{{ $user->bio }}</div>
                                <div class="small mt-2">
                                    <span>
                                        <i class="fa fa-calendar-alt mr-1 text-black-50"></i>
                                        Joined {{ Carbon::parse($user->created_at)->format("F Y") }}
                                    </span>
                                    @if ($user->location)
                                    <span class="ml-3">
                                        <a class="text-dark" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/{{ urlencode($user->location) }}">
                                            <i class="fa fa-compass mr-1 text-black-50"></i>
                                            {{ $user->location }}
                                        </a>
                                    </span>
                                    @endif
                                    @if ($user->company)
                                    <span class="ml-3">
                                        <i class="fa fa-briefcase mr-1 text-black-50"></i>
                                        {{ $user->company }}
                                    </span>
                                    @if ($user->isStaff)
                                    <span class="badge rounded-pill bg-primary ml-1">Staff</span>
                                    @endif
                                    @endif
                                </div>
                                <div class="mt-3">
                                    @livewire('user.follow', [
                                        'user' => $user
                                    ], key($user->id))
                                </div>
                            </span>
                        </div>
                    </li>
                @endforeach
                <div class="mt-3">
                    {{ $users->appends(request()->input())->links() }}
                </div>
                @endif
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/search/search.blade.php
@extends('layouts.app')

@section('pageTitle', 'Search ·')
@section('title', 'Search ·')
@section('description', 'Browse questions and discuss, answer, give feedbacks, etc.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="h4 font-weight-normal">
                <i class="fa fa-search mr-2"></i>
                <span>
                    Search more than
                    <span class="font-weight-bold">{{ $random }}</span>
                </span>
            </div>
            <form action="/search/tasks" method="GET" role="search">
                @csrf
                <div class="input-group mt-3">
                    <input type="text" class="form-control" name="q" placeholder="Search Taskord" autofocus>
                    <button type="submit" class="btn btn-secondary">Search</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection