routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

Route::group(['middleware' => ['throttle:30,1']], function () {
    // Home
    Route::get('/', [HomeController::class, 'index'])->name('home');

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('export', [UserController::class, 'exportAccount'])->name('export');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::get('suspended', [UserController::class, 'suspended'])->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::get('users', [AdminController::class, 'users'])->name('users');
        Route::get('tasks', [AdminController::class, 'tasks'])->name('tasks');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::get('', [PatronController::class, 'patron'])->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::get('tasks', [TaskController::class, 'tasks'])->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('reputation', 'pages.reputation')->name('reputation');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::get('open', [PagesController::class, 'open'])->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    Route::get('meetups', [MeetupController::class, 'meetups'])->name('meetups')->middleware('staff');

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status
    Route::group(['prefix' => 'status'], function () {
        Route::get('ping', [StatusController::class, 'ping']);
        Route::get('redis', [StatusController::class, 'redis']);
        Route::get('memcached', [StatusController::class, 'memcached']);
    });
});

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Hovercard
Route::group(['prefix' => 'hovercard'], function () {
    Route::get('user/{id}', [UserController::class, 'hovercard']);
    Route::get('product/{id}', [ProductController::class, 'hovercard']);
});

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('pageTitle', 'About ·')
@section('title', 'About ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Heading</span>
            <div>Sub-heading</div>
        </div>
        <div class="card-body">
            Soon
        </div>
    </div>
</div>
@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('pageTitle', 'About ·')
@section('title', 'About ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
<div class="row justify-content-center" style="height:70vh">
    <div class="col-lg-7 mt-5">
        @auth
        @php
        $username = "@".Auth::user()->username;
        $email = urlencode(Auth::user()->email);
        $url = "https://tally.so/embed/5mVVam?username=".$username."&email=".$email."&transparentBackground=1";
        @endphp
        <iframe
            src="{{$url}}"
            width="100%"
            height="100%"
            frameborder="0"
            marginheight="0"
            marginwidth="0"
        ></iframe>
        @else
        <iframe
            src="https://tally.so/embed/63lL53?transparentBackground=1"
            width="100%"
            height="100%"
            frameborder="0"
            marginheight="0"
            marginwidth="0"
        ></iframe>
        @endauth
    </div>
</div>
</div>
@endsection

resources/views/pages/deals.blade.php
@extends('layouts.app')

@section('pageTitle', 'Deals ·')
@section('title', 'Deals ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Deals</span>
            <div>Discounts and special deals for Taskord members. Only available for patrons.</div>
            <div>
                <a href="https://taskord.typeform.com/to/RQFk3SXy" target="_blank">Add your product</a>
            </div>
            @auth
            @if (Auth::user()->staffShip)
            <button type="button" class="mt-2 btn btn-success text-white" data-toggle="modal" data-target="#newQuestionModal">
                <i class="fa fa-plus mr-1"></i>
                Add a Deal
            </button>
            @livewire('pages.create-deal')
            @endif
            @endauth
        </div>
        <div class="card-body">
            @if (count($deals) === 0)
            <x-empty icon="gifts" text="No deals found" />
            @endif
            @foreach ($deals as $deal)
                <div class="d-flex align-items-center {{ $loop->last ? '' : 'mb-5' }}">
                    <div>
                        <img class="rounded avatar-100" src="{{ $deal->logo }}" />
                    </div>
                    <div class="ml-4">
                        <span class="h4">
                            {{ $deal->name }}
                        </span>
                        <span class="h5">
                            <span class="align-text-top badge bg-success font-weight-normal p-1 ml-1">{{ $deal->offer }}% OFF</span>
                        </span>
                        <div class="h6 mt-3">{{ $deal->description }}</div>
                        <div class="mt-2">
                            <a href="{{ $deal->website }}" target="_blank">{{ $deal->website }}</a>
                        </div>
                        @auth
                        @if (Auth::user()->isPatron)
                        @if ($deal->coupon)
                        <div class="mt-2">
                            Coupon Code
                            <code class="ml-2 font-weight-bold">
                                {{ $deal->coupon }}
                            </code>
                        </div>
                        @else
                        <div class="mt-2 font-weight-bold">
                            <a href="{{ $deal->referral }}" target="_blank">
                                Click here to get your deal
                            </a>
                        </div>
                        @endif
                        @else
                        <div class="mt-2">
                            <a class="text-black-50" href="{{ route('patron.home') }}">You must be a patron to see coupon code.</a>
                        </div>
                        @endif
                        @endauth
                        @guest
                        <div class="mt-2">
                            <a class="text-black-50" href="{{ route('login') }}">Login to view coupon code.</a>
                        </div>
                        @endguest
                        @auth
                        @endauth
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/pages/open.blade.php
@extends('layouts.app')

@section('pageTitle', 'Open ·')
@section('title', 'Open ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Heading</span>
            <div>Sub-heading</div>
        </div>
        <div class="card-body">
            Soon
        </div>
    </div>
</div>
@endsection

resources/views/pages/patron.blade.php
@extends('layouts.app')

@section('pageTitle', 'Patron ·')
@section('title', 'Patron ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="mb-4 text-center">
        <img src="/images/patron.svg" width="100" />
    </div>
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Become a Patron</span>
            <div>Support Taskord by becoming a Patron.</div>
        </div>
        <div class="card-body">
            <div class="row align-items-center font-monospace">
                <div class="col-lg-8">
                    <div class="font-weight-bold mb-3">You get the following benefits</div>
                    <ul>
                        <li>🌑 Enable Awesome Dark Mode</li>
                        <li>💬 Patrons only discussion to make it more meaningful</li>
                        <li>🔒 Make your tasks private and get personal things done</li>
                        <li>🤝 Show off your support with the Patron badge</li>
                        <li>👍 Fund on-going development of the platform and server fee</li>
                        <li>More coming soon...</li>
                    </ul>
                </div>
                <div class="col-sm">
                    @auth
                    @if (Auth::user()->isPatron and Auth::user()->patron()->count() === 1)
                    <div class="text-center">
                        <div class="h5">
                            {{ Emoji::redHeart() }}
                            You are already a patron!
                        </div>
                        <a class="text-primary" href="{{ route('user.settings.patron') }}">
                            Go to settings
                        </a>
                    </div>
                    @else
                    <a
                        class="paddle_button btn btn-block btn-primary"
                        data-theme="none"
                        data-product="619848"
                        data-message="Support $5/month for Taskord!"
                        data-email="{{ Auth::user()->email }}"
                    >
                        Support $5/month
                    </a>
                    <a
                        class="paddle_button btn btn-block btn-primary"
                        data-theme="none"
                        data-product="621377"
                        data-message="Support $10/month for Taskord!"
                        data-email="{{ Auth::user()->email }}"
                    >
                        Support $10/month
                    </a>
                    <a
                        class="paddle_button btn btn-block btn-primary"
                        data-theme="none"
                        data-product="621379"
                        data-message="Support $20/month for Taskord!"
                        data-email="{{ Auth::user()->email }}"
                    >
                        Support $20/month
                    </a>
                    <a
                        class="paddle_button btn btn-block btn-primary"
                        data-theme="none"
                        data-product="621380"
                        data-message="Support $50/month for Taskord!"
                        data-email="{{ Auth::user()->email }}"
                    >
                        Support $50/month
                    </a>
                    <a
                        class="paddle_button btn btn-block btn-primary"
                        data-theme="none"
                        data-product="629491"
                        data-message="Support $100 onetime for lifetime pro in Taskord!"
                        data-email="{{ Auth::user()->email }}"
                    >
                        Support $100 onetime
                    </a>
                    @endif
                    @endauth
                    @guest
                    <a class="btn btn-block btn-success text-white" href="{{ route('login') }}">
                        Login to support!
                    </a>
                    @endguest
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.paddle.com/paddle/paddle.js"></script>
<script type="text/javascript">
	Paddle.Setup({ vendor: 120187 });
</script>
@endsection

resources/views/pages/privacy.blade.php
@extends('layouts.app')

@section('pageTitle', 'Privacy ·')
@section('title', 'Privacy ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Privacy Policy</span>
            <div>Web Site Privacy Policy</div>
        </div>
        <div class="card-body">
            <div>
                Taskord built the Taskord app as an Open Source app. This SERVICE is provided by Taskord at no cost and is intended for use as is.
            </div>
            <div>
                This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.
            </div>
            <div>
                If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.
            </div>
            <div>
                The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Taskord unless otherwise defined in this Privacy Policy.
            </div>
            <h5 class="mt-4">Information Collection and Use</h5>
            <div>
                For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information. The information that I request will be retained on your device and is not collected by me in any way.
            </div>
            <h5 class="mt-4">Log Data</h5>
            <div>
                I want to inform you that whenever you use my Service, in a case of an error in the app I collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics.
            </div>
            <h5 class="mt-4">Cookies</h5>
            <div>
                Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.
            </div>
            <div>
                This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.
            </div>
            <h5 class="mt-4">Service Providers</h5>
            <div>
                I may employ third-party companies and individuals due to the following reasons:
            </div>
            <div class="mt-3">
                <ul>
                    <li>To facilitate our Service;</li>
                    <li>To provide the Service on our behalf;</li>
                    <li>To perform Service-related services; or</li>
                    <li>To assist us in analyzing how our Service is used.</li>
                </ul>
            </div>
            <div>
                I want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
            </div>
            <h5 class="mt-4">Security</h5>
            <div>
                I value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and I cannot guarantee its absolute security.
            </div>
            <h5 class="mt-4">Links to Other Sites</h5>
            <div>
                This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
            </div>
            <h5 class="mt-4">Children’s Privacy</h5>
            <div>
                These Services do not address anyone under the age of 13. I do not knowingly collect personally identifiable information from children under 13. In the case I discover that a child under 13 has provided me with personal information, I immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact me so that I will be able to do necessary actions.
            </div>
            <h5 class="mt-4">Changes to This Privacy Policy</h5>
            <div>
                I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page.
            </div>
            <div>
                This policy is effective as of 2020-09-10
            </div>
            <h5 class="mt-4">Contact Us</h5>
            <div>
                If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at yo@taskord.com.
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/reputation.blade.php
@extends('layouts.app')

@section('pageTitle', 'Reputation ·')
@section('title', 'Reputation ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Heading</span>
            <div>Sub-heading</div>
        </div>
        <div class="card-body">
            Soon
        </div>
    </div>
</div>
@endsection

resources/views/pages/security.blade.php
@extends('layouts.app')

@section('pageTitle', 'Security ·')
@section('title', 'Security ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Security</span>
            <div>Reporting Vulnerabilities to Taskord</div>
        </div>
        <div class="card-body">
            <div>
                Found a vulnerability in our systems? Fill out this form <a href="https://airtable.com/shrN0O8155kbi61Jl" target="_blank">here</a>. You'll hear back from us within two weeks at the absolute latest, and we'll let you know:
            </div>
            <div class="mt-3">
                <ul>
                    <li>If it's been reported previously,</li>
                    <li>Whether or not we think it's a valid issue,</li>
                    <li>And if it's eligible for a reward.</li>
                </ul>
            </div>
            <h5 class="mt-4">Security Guidelines and Etiquette</h5>
            <div>
                Please read and follow these guidelines prior to sending in any reports.
            </div>
            <div class="mt-3">
                <ol>
                    <li>
                        <div>Do not test vulnerabilities in public. We ask that you do not attempt any vulnerabilities, rate-limiting tests, exploits, or any other security/bug-related findings if it will impact another community member. This means you should not leave comments on someone else’s tasks and questions, or otherwise, impact their experience on the platform.</div>
                        <div class="mt-1">Note that we are open source and have <a href="https://gitlab.com/taskord/taskord/-/blob/main/docs/installation.md" target="_blank">documentation</a> available if you're interested in setting up a dev environment for the purposes of testing.</div>
                    </li>
                    <li class="mt-2">
                         Do not report similar issues or variations of the same issue in different reports. Please report any similar issues in a single report. It's better for both parties to have this information in one place where we can evaluate it all together. Please note any and all areas where your vulnerability might be relevant. You will not be penalized or receive a lower reward for streamlining your report in one place vs. spreading it across different areas.
                    </li>
                    <li class="mt-2">
                        The following domains are not eligible for our bounty program as they are hosted by or built on external services:
                        <div class="mt-2">
                            <ul>
                                <li>
                                    <a href="https://status.taskord.com">status.taskord.com</a> (UptimeRobot)
                                </li>
                            </ul>
                        </div>
                        <div class="mt-1">
                            We've listed the service provider of each of these domains so that you might contact them if you wish to report the vulnerability you found.
                        </div>
                    </li>
                    <li class="mt-2">
                        DoS (Denial of Service) vulnerabilities should not be tested for more than a span of 5 minutes. Be courteous and reasonable when testing any endpoints on dev.to as this may interfere with our monitoring. If we discover that you are testing DoS disruptively for prolonged periods of time, we may restrict your award, block your IP address, or remove your eligibility to participate in the program.
                    </li>
                    <li class="mt-2">
                        Please be patient with us after sending in your report. We’d appreciate it if you avoid messaging us to ask about the status of your report. Our team will get back to you as quickly as we are able. It is okay to inquire about the status of your report if you haven’t heard from us 2 weeks after sending it in. Otherwise, we ask that you please wait patiently for us to contact you, unless you have more information relevant to the vulnerability that you’d like to share.
                    </li>
                </ol>
            </div>
            <h5 class="mt-4">Vulnerability Assessment and Reward</h5>
            <div>
                Vulnerabilities are assessed via <a href="https://bugcrowd.com/vulnerability-rating-taxonomy" target="_blank">BugCrowd's taxonomy rating</a> and our judgment. For now we provide you lifetime Taskord Patron for free!
            </div>
        </div>
    </div>
</div>
@endsection